### ISSUE TITLE
docker compose build fails with...

### ISSUE THREAD

**Issue by jotelha** [ContactEngineering/topobank-stack-development#7]
...  => ERROR [topobank_development_celeryworker stage-0 21/23] RUN addgroup django --gid 0     && adduser --ingroup django --uid 0 --gecos "" --disabled-password django                                         0.4s

**Comment by jotelha** [comment]
Need to build with
```
TOPOBANK_UID=$(id -u) TOPOBANK_GID=$(id -g) docker compose build
```
as documented in README.

**Comment by mcrot** [comment]
Or add the ids in the `.env` file.
